name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

 strategy:
            matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run cypress-parallel
          config-file: cypress.config.ts