name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
<<<<<<< HEAD
=======
    strategy:
      matrix:
        # don't fail the entire matrix on failure
       #fail-fast: false
        # run copies of the current job in parallel
        containers: [1, 2, 3]
>>>>>>> 86a9319bf9b7d2f182c9222f923fe12cc1931a72


    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run runnerDesc
          config-file: cypress.config.ts
